- src/test/resources/config/testEA_Docx.xml
targetParameter xslTransformerFactory is missing in testEA_Docx.xml. Without this parameter, an error is given by ShapeChange:
> Parameter 'outputFormat' contains 'DOCX' and/or 'FRAMEHTML'. These formats require an XSLT 2.0 processor, which should be set via the configuration parameter 'xslTransformerFactory'. That parameter was not found, and the default TransformerFactory implementation is not 'net.sf.saxon.TransformerFactoryImpl' (which is known to be an XSLT 2.0 processor); ensure that the parameter is configured correctly.
The tests currently don't fail, since the system property `javax.xml.transform.TransformerFactory` is set to `net.sf.saxon.TransformerFactoryImpl` in code run earlier and is not reset.
The error occurs when running ShapeChange directly on testEA_Docx.xml, or when …
> Add xslTransformerFactory in testEA_Docx.xml

- src/test/java/de/interactive_instruments/ShapeChange/ApplicationSchemaMetadataTest.java
- src/test/java/de/interactive_instruments/ShapeChange/AssociationClassMapperTest.java
- src/test/java/de/interactive_instruments/ShapeChange/AttributeCreatorTest.java
- src/test/java/de/interactive_instruments/ShapeChange/BasicTest.java
- src/test/java/de/interactive_instruments/ShapeChange/FOL2SchematronTest.java
- src/test/java/de/interactive_instruments/ShapeChange/FeatureCatalogueTest.java
- src/test/java/de/interactive_instruments/ShapeChange/FlattenerTest.java
- src/test/java/de/interactive_instruments/ShapeChange/JSONTest.java
- src/test/java/de/interactive_instruments/ShapeChange/MinimalAndTesttXmiModelTest.java
- src/test/java/de/interactive_instruments/ShapeChange/OntologyTest.java
- src/test/java/de/interactive_instruments/ShapeChange/ProfilerTest.java
- src/test/java/de/interactive_instruments/ShapeChange/ReplicationXMLSchemaTest.java
- src/test/java/de/interactive_instruments/ShapeChange/SQLTest.java
- src/test/java/de/interactive_instruments/ShapeChange/VariousFunctionalityTest.java
- src/test/java/de/interactive_instruments/ShapeChange/WindowsBasicTest.java
- src/test/java/de/interactive_instruments/ShapeChange/XMLSchemaTest.java
Running all the tests takes quite a long time. Often it would be handy to be able to run a handful of tests, e.g. when working on a particular target. Especially if there is an error somewhere, and one would like to focus on fixing it, and rerunning tests on only the affected code.
Therefore, a proposal to split the class BasicTest, which contains one single test with all test logic, into several test classes, each containing one or more test methods.
> Split class BasicTest into multiple test classes

- src/main/java/de/interactive_instruments/ShapeChange/Model/InfoImpl.java
- src/main/java/de/interactive_instruments/ShapeChange/Options.java
- src/main/java/de/interactive_instruments/ShapeChange/Target/XmlSchema/XsdDocument.java
This commit addresses #53 by searching for simple type mappings in the
direct or indirect supertypes of a basic type, to identify the XSD type
that should be used in the check if a particular facet is supported.
The commit also addresses #54, by adding 'documentation' as a possible
replacement in InfoImpl.derivedDocumentation(...).
> improves facet detection, adds documentation to derivedDocumentation()

- src/main/java/de/interactive_instruments/ShapeChange/ShapeChangeResult.java
- src/main/java/de/interactive_instruments/ShapeChange/Transformation/Flattening/Flattener.java
Log messages in the Flattener are useful when using regular expressions, to make it easier for users to discover possible typos or other mistakes in these regular expressions.
> Add logging to Flattener when using regexes

- src/main/java/de/interactive_instruments/ShapeChange/Target/SQL/ReplicationSchemaVisitor.java
Set minOccurs according to the multiplicity of a property
when rule rule-sql-prop-replicationSchema-optional is not enabled.
> Update setting of minOccurs in ReplicationSchemaVisitor

- src/main/java/de/interactive_instruments/ShapeChange/Model/EA/EADocument.java
- src/main/java/de/interactive_instruments/ShapeChange/ShapeChangeResult.java
Add log statements to indicate that ShapeChange is (1) connecting to
, (2) has connected, (3) is reading and (4) has read an eap-file. This
information is useful as it can take quite some time to do this, and
gives some information to the user as to what ShapeChange is doing.
A log file will then look as follows:
I ---------- Semantic validation of ShapeChange configuration: START ----------
I <...>
I ---------- Semantic validation of ShapeChange configuration: COMPLETE ----------
I Connecting to pathToFolder\fileName.eap
I Connected to pathToFolder\fileName.eap
I Starting reading pathToFolder\fileName.eap
I Finished reading pathToFolder\fileName.eap
I (Converter.java) Now processing transformation '<...>' for input ID: 'INPUT'.
> Add log statements when connecting to and reading an eap-file

- src/main/java/de/interactive_instruments/ShapeChange/Model/InfoImpl.java
- src/main/java/de/interactive_instruments/ShapeChange/Options.java
- src/main/java/de/interactive_instruments/ShapeChange/ShapeChangeResult.java
Add an error message in the result when a default encoding rule is specified
for a certain platform but this default encoding rule is not present in the ShapeChange
configuration. This adds useful information for the user, as this misconfiguraton
likely will result in other errors or issues later on.
> Add error message when a default encoding rule is specified but not configured

- src/main/java/de/interactive_instruments/ShapeChange/Target/SQL/SqlBuilder.java
- src/main/java/de/interactive_instruments/ShapeChange/Target/SQL/SqlConstants.java
- src/test/resources/sql/dataTypeEncoding_oneToMany/reference/oneTable/INPUT/Test_Schema.sql
- src/test/resources/sql/dataTypeEncoding_oneToMany/reference/severalTables/INPUT/Test_Schema.sql
- src/test/resources/sql/identifierStereotype/reference/ddl/F_inheritance/Test_Schema.sql
Make the reference column to the owning feature obligatory (NOT NULL).
An instance of a data type cannot exist alone, it only exists within
the context of the instance of a feature type.
> Update DDL encoding of complex data types

- src/main/java/de/interactive_instruments/ShapeChange/Transformation/TransformationManager.java
Add logging during the identification of model elements for which a
tagged value is to be (re-)set. This identification is done by means of
regular expressions, thus messages regarding whether or not the
name/stereotype matches are useful for troubleshooting.
> Add logging when setting tagged values

- src/main/java/de/interactive_instruments/ShapeChange/Target/SQL/ReplicationSchemaVisitor.java
No maxLength restriction on strings is set unless the size tagged value
is set explicitly on the property.
> ReplicationSchema: no maxLength unless size set

- src/main/java/de/interactive_instruments/ShapeChange/Converter.java
- src/main/java/de/interactive_instruments/ShapeChange/Model/InfoImpl.java
- src/main/java/de/interactive_instruments/ShapeChange/Options.java
- src/test/java/de/interactive_instruments/ShapeChange/BasicTest.java
- src/test/java/de/interactive_instruments/ShapeChange/TargetModeTest.java
- src/test/resources/config/testXMI_targetMode.xml
A target must appear in the configuration as enabled if the target is
configured multiple times and one or more of its occurrences are
enabled. Otherwise the rule matching can give wrong results.
> Fix configuration loading of the process mode of targets

- src/main/java/de/interactive_instruments/ShapeChange/Target/SQL/ReplicationSchemaVisitor.java
- src/main/java/de/interactive_instruments/ShapeChange/Target/SQL/SqlDdl.java
Add the possiblity to select a schema whose namespace settings should be
used in the replication schema generation. This functionality is needed
after the conversion of the SqlDdl target to a single target.
Make sure that the reference to a simple type representing an
enumeration uses the correct namespace abbreviation.
> Update namespace handling ReplicationSchema

- src/main/java/de/interactive_instruments/ShapeChange/Converter.java
- src/main/java/de/interactive_instruments/ShapeChange/Target/SQL/SqlDdl.java
- src/main/java/de/interactive_instruments/ShapeChange/Target/TargetUtil.java
SingleTargets operate on several schemas at once, in some cases
it is necesssary to be able to specify a main schema.
The properties of this main schema (version, namespaces, etc.)
can then be used in the further processing in the single target.
> Add concept of "main schema" in Converter and in SqlDdl

- .gitignore
New files, such as Java classes in package Target or one of its
subpackages are not ignored anymore by git.
Before: git check-ignore -v src/main/java/de/interactive_instruments/ShapeChange/Target/NewClass.java
.gitignore:15:target/   src/main/java/de/interactive_instruments/ShapeChange/Target/NewClass.java
After: git check-ignore -v src/main/java/de/interactive_instruments/ShapeChange/Target/NewClass.java
(no output, thus this path is not ignored)
> New classes in package Target are not ignored

- src/main/java/de/interactive_instruments/ShapeChange/ShapeChangeResult.java
The encoding for the log files should be UTF-8 and not depend on the
platform the application is run on.
> Create the resulting log files with UTF-8 encoding

- .gitignore
- src/main/java/de/interactive_instruments/ShapeChange/Model/EA/AssociationInfoEA.java
- src/main/java/de/interactive_instruments/ShapeChange/Model/EA/ClassInfoEA.java
- src/main/java/de/interactive_instruments/ShapeChange/Model/EA/OperationInfoEA.java
- src/main/java/de/interactive_instruments/ShapeChange/Model/EA/PackageInfoEA.java
- src/main/java/de/interactive_instruments/ShapeChange/Model/EA/PropertyInfoEA.java
- src/main/java/de/interactive_instruments/ShapeChange/Model/Info.java
- src/main/java/de/interactive_instruments/ShapeChange/Options.java
- src/main/java/de/interactive_instruments/ShapeChange/ShapeChangeResult.java
- src/main/java/de/interactive_instruments/ShapeChange/Util/ea/EAGeneralUtil.java
Update validateStereotypesCache() for EA models: refactor to remove duplicated code.
> validateStereotypesCache() for EA models

- src/main/java/de/interactive_instruments/ShapeChange/Target/GeoPackage/GeoPackageTemplate.java
A code list can be modelled as having values in the UML model. Take
this into account by logging a warning ("not yet supported"),
ignoring the code list and continuing execution.
> Ignore code list values in GeoPackage generation

- src/main/resources/schema/ShapeChangeConfiguration.xsd
- src/test/java/de/interactive_instruments/ShapeChange/GeoPackageTest.java
- src/test/resources/gpkg/basic/test_gpkg_basic_2srs.xml
- src/test/resources/gpkg/basic/test_gpkg_basic_2srs_runWithSCXML.xml
E.g.
```xml
<GeoPackageSrsDefinitions>
<srsDefinition>
<GeoPackageSrsDefinition>
<srsName>ETRS89 / UTM zone 32N</srsName>
<srsId>25832</srsId>
<organization>EPSG</organization>
<organizationCoordSysId>25832</organizationCoordSysId>
<definition>PROJCS[...]</definition>
</GeoPackageSrsDefinition>
</srsDefinition>
<srsDefinition>
<GeoPackageSrsDefinition>
<srsName>ETRS89 / UTM zone 33N</srsName>
<srsId>25833</srsId>
<organization>EPSG</organization>
<organizationCoordSysId>25833</organizationCoordSysId>
<definition>PROJCS[...]</definition>
</GeoPackageSrsDefinition>
</srsDefinition>
</GeoPackageSrsDefinitions>
```
Support for adding several definitions in `gpkg_spatial_ref_sys` is
already present in GeoPackageTemplate.
> Allow more than one spatial reference system in the configuration

- src/main/java/de/interactive_instruments/ShapeChange/Target/GeoPackage/GeoPackageTemplate.java
Otherwise, all model elements are suppressed when rule `rule-gpkg-all-notEncoded` is enabled.
> Suppress conversion only when tag gpkgEncodingRule = notEncoded

- pom.xml
- src/main/java/de/interactive_instruments/ShapeChange/Target/GeoPackage/GeoPackageConstants.java
- src/main/java/de/interactive_instruments/ShapeChange/Target/GeoPackage/GeoPackageTemplate.java
- src/main/java/de/interactive_instruments/ShapeChange/Target/GeoPackage/GeoPackageTemplateConfigurationValidator.java
Improvements: see commit messages.
A note on the changes for `gpkg_data_columns`: the idea behind it is that it makes more sense to describe all columns instead of just using the columns that refer to enumerations. From the spec:
> The schema extension provides a means to describe the columns of tables in a GeoPackage with more detail than can be captured by the SQL table definition directly. The information provided by this extension can be used by applications to, for instance, present data contained in a GeoPackage in a more user-friendly fashion or implement data validation logic.
There is no hard enum validation in SQLite anyway - for that, check constraints should be used instead, I guess - the contents of the `gpkg_data_columns` and `gpkg_data_column_constraints` are mainly for use …
> Gpkg improvements

- src/docs/asciidoc/get started/Get_Started.adoc
- src/docs/asciidoc/get started/Typical_problems.adoc
It is possible to use ShapeChange on EA files without having to copy SSJavaCOM64.dll or SSJavaCOM.dll to a folder that the Java Virtual Machine automatically searches when loading libraries.
See this post on the EA forum for more information: https://sparxsystems.com/forums/smf/index.php/topic,46812.msg273672.html.
> Describe use of java.library.path

- src/main/java/de/interactive_instruments/ShapeChange/Target/GeoPackage/GeoPackageTemplate.java
Make sure that the Schema extension is always registered, also when no enumerations are present in the input model.
Fixes #322.
> Update the creation of the tables of the GPKG Schema extension
